name: Call Frontend Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  ci-workflow:
    uses: Mauricio-Camilo-AWS-Projects/CI-CD-Workflows/.github/workflows/frontend-ci.yml@main

    # secrets:
    #   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}